version: '3.9'
services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # working_dir: /app
    environment:
      - NODE_ENV=production
      - EPHEMERA_HOST=${EPHEMERA_HOST:-localhost:3000}
      - EPHEMERA_PORT=3000
      - EPHEMERA_DB_HOST=mariadb
      - EPHEMERA_DB_PORT=3306
      - EPHEMERA_DB_USER=ephemera
      - EPHEMERA_DB_PASSWORD=${EPHEMERA_DB_PASSWORD:-ephemera_pw}
      - EPHEMERA_DB_NAME=ephemera_db
    volumes:
      - backend_data:/app/backend/data
    depends_on:
      - mariadb
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    # working_dir: /app
    environment:
      - NODE_ENV=production
      - EPHEMERA_HOST=${EPHEMERA_HOST:-localhost:3000}
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${EPHEMERA_DB_ROOT_PASSWORD:-root_pw}
      - MARIADB_DATABASE=ephemera_db
      - MARIADB_USER=ephemera
      - MARIADB_PASSWORD=${EPHEMERA_DB_PASSWORD:-ephemera_pw}
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
  peer:
    build:
      context: .
      dockerfile: ./peer/Dockerfile
    restart: unless-stopped
    environment:
      - EPHEMERA_INTERNAL_HOST=${EPHEMERA_INTERNAL_HOST:-0.0.0.0:8080}
      - EPHEMERA_EXTERNAL_HOST=${EPHEMERA_EXTERNAL_HOST:-localhost:3000}

volumes:
  mariadb_data:
  backend_data:
